# Site settings
title: Alana Darcher
description: human brains & co.
url: https://a-darcher.github.io # Your GitHub Pages URL

# Build settings
#theme: minima # You can change the theme or use your own
markdown: kramdown
permalink: pretty

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE

